---
- name: Blue-Green Deployment for Web Application
  hosts: webservers
  become: yes
  vars:
    app_name: myapp
    blue_env_path: /var/www/myapp-blue
    green_env_path: /var/www/myapp-green
    active_env_file: /etc/nginx/conf.d/active_env.conf
    repo_url: "https://github.com/example/myapp.git"
    branch: "main"
    nginx_config_path: /etc/nginx/conf.d/default.conf

  tasks:
    - name: Check current active environment
      command: cat {{ active_env_file }}
      register: active_env
      ignore_errors: yes

    - name: Set next environment
      set_fact:
        next_env: "{{ 'green' if active_env.stdout == 'blue' else 'blue' }}"

    - name: Deploy code to next environment
      git:
        repo: "{{ repo_url }}"
        dest: "{{ '/var/www/myapp-' + next_env }}"
        version: "{{ branch }}"
        force: yes

    - name: Install dependencies (Node.js example)
      command: npm install
      args:
        chdir: "{{ '/var/www/myapp-' + next_env }}"
      ignore_errors: no

    - name: Build application
      command: npm run build
      args:
        chdir: "{{ '/var/www/myapp-' + next_env }}"
      ignore_errors: no

    - name: Update Nginx to point to new environment
      template:
        src: nginx_blue_green.j2
        dest: "{{ nginx_config_path }}"
      notify: Restart Nginx
      vars:
        current_env_path: "{{ '/var/www/myapp-' + next_env }}"

    - name: Update active environment flag
      copy:
        content: "{{ next_env }}"
        dest: "{{ active_env_file }}"
        mode: '0644'

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
